[package]
name = "rusttype"
version = "0.5.0"
authors = [
    "Dylan Ede <dylanede@googlemail.com>",
    "Jeremy Soller <jackpot51@gmail.com>"
]
description = """
A pure Rust alternative to libraries like FreeType.

RustType provides an API for loading, querying and rasterising TrueType fonts.

It also provides an implementation of a dynamic GPU glyph cache for hardware font rendering.
"""
documentation = "https://docs.rs/rusttype"
homepage = "https://github.com/redox-os/rusttype"
repository = "https://github.com/redox-os/rusttype"
readme = "README.md"
license = "MIT / Apache-2.0"
keywords = ["font", "truetype", "opentype", "ttf", "otf"]
exclude = ["/fonts/**"]

[package.metadata.docs.rs]
features = ["gpu_cache"]

[dependencies]
arrayvec = "0.4"
stb_truetype = "0.2.2"
ordered-float = "0.5"
approx = "0.1"
linked-hash-map = { version = "0.5", optional = true }
fnv = { version = "1", optional = true }

[dev-dependencies]
glium = "0.20"
unicode-normalization = "0.1"
image = "0.18"

[features]
# Compiles benchmark code, to be avoided normally as this currently requires nightly rust
bench = ["gpu_cache"]
gpu_cache = ["linked-hash-map", "fnv"]

[[example]]
name = "gpu_cache"
required-features = ["gpu_cache"]

[[example]]
name = "image"

[[example]]
name = "simple"
